{% set name = "setuptools-cythonize" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5ed4893538cc79db1a24df3d66c4b7c384d377afec6549c1eb1e4d0f89ade0e1
  patches:
    - remove-mingw32.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - m2-patch  # [win]
  host:
    - python
    - pip
    - wheel
    - cython
  run:
    - python
    - wheel
    - cython
    - setuptools

test:
  imports:
    - setuptools_cythonize

about:
  home: https://github.com/anxuae/setuptools-cythonize
  license: MIT
  license_family: MIT
  # license file manually packaged. Please see https://github.com/anxuae/setuptools-cythonize/pull/4
  license_file: LICENSE
  summary: distutils classes to compile Python source code into C code using Cython

extra:
  recipe-maintainers:
    - tschoonj
