{% set name = "setuptools-cythonize" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5a44e3ef90d3be6ae4cdf49c910fc6d70e0a3e29d55b165f5eb8f34ac0e1109f

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - wheel
    - cython
    - setuptools
  run:
    - python >={{ python_min }}
    - wheel
    - cython
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - setuptools_cythonize

about:
  home: https://github.com/anxuae/setuptools-cythonize
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: distutils classes to compile Python source code into C code using Cython

extra:
  recipe-maintainers:
    - tschoonj
